name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.1.1 <4.0.0"

fonts:
  - family: SF-Pro
    fonts:
      - asset: fonts/SF-Pro-Text-Regular.otf
      - asset: fonts/SF-Pro-Text-Bold.otf
        weight: 700

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_blue_plus: ^1.31.15
  get: ^4.6.6
  permission_handler: ^11.3.0
  google_fonts: ^6.1.0
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/drone_image.jpg
    - assets/battery_icon.jpg
